### ISSUE TITLE
0.98a checklist

### ISSUE THREAD

**Issue by WhalleyT** [Pathogen-Genomics-Cymru/lodestone#88]
- [x] decontamination sub workflow
- [x] bug fix for miscalculated proportion of reads second pass
- [ ] permissive flag
- [x] explainer on singularity containers
- [ ] new stub runs
